// Code generated by MockGen. DO NOT EDIT.
// Source: d:\\Code Store\\Github\\iqibla-backend\\internal\\repository\\cart.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/hanifbg/landing_backend/internal/model/entity"
)

// MockCartRepository is a mock of CartRepository interface.
type MockCartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCartRepositoryMockRecorder
}

// MockCartRepositoryMockRecorder is the mock recorder for MockCartRepository.
type MockCartRepositoryMockRecorder struct {
	mock *MockCartRepository
}

// NewMockCartRepository creates a new mock instance.
func NewMockCartRepository(ctrl *gomock.Controller) *MockCartRepository {
	mock := &MockCartRepository{ctrl: ctrl}
	mock.recorder = &MockCartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartRepository) EXPECT() *MockCartRepositoryMockRecorder {
	return m.recorder
}

// CreateCart mocks base method.
func (m *MockCartRepository) CreateCart(cart *entity.Cart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCart", cart)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCart indicates an expected call of CreateCart.
func (mr *MockCartRepositoryMockRecorder) CreateCart(cart interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCart", reflect.TypeOf((*MockCartRepository)(nil).CreateCart), cart)
}

// CreateCartItem mocks base method.
func (m *MockCartRepository) CreateCartItem(item *entity.CartItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCartItem", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCartItem indicates an expected call of CreateCartItem.
func (mr *MockCartRepositoryMockRecorder) CreateCartItem(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCartItem", reflect.TypeOf((*MockCartRepository)(nil).CreateCartItem), item)
}

// DeleteCartItem mocks base method.
func (m *MockCartRepository) DeleteCartItem(cartID, variantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartItem", cartID, variantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCartItem indicates an expected call of DeleteCartItem.
func (mr *MockCartRepositoryMockRecorder) DeleteCartItem(cartID, variantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartItem", reflect.TypeOf((*MockCartRepository)(nil).DeleteCartItem), cartID, variantID)
}

// FindCartByID mocks base method.
func (m *MockCartRepository) FindCartByID(cartID string) (*entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCartByID", cartID)
	ret0, _ := ret[0].(*entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCartByID indicates an expected call of FindCartByID.
func (mr *MockCartRepositoryMockRecorder) FindCartByID(cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCartByID", reflect.TypeOf((*MockCartRepository)(nil).FindCartByID), cartID)
}

// FindCartItem mocks base method.
func (m *MockCartRepository) FindCartItem(cartID, variantID string) (*entity.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCartItem", cartID, variantID)
	ret0, _ := ret[0].(*entity.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCartItem indicates an expected call of FindCartItem.
func (mr *MockCartRepositoryMockRecorder) FindCartItem(cartID, variantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCartItem", reflect.TypeOf((*MockCartRepository)(nil).FindCartItem), cartID, variantID)
}

// GetCartItemsByCartID mocks base method.
func (m *MockCartRepository) GetCartItemsByCartID(cartID string) ([]entity.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartItemsByCartID", cartID)
	ret0, _ := ret[0].([]entity.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartItemsByCartID indicates an expected call of GetCartItemsByCartID.
func (mr *MockCartRepositoryMockRecorder) GetCartItemsByCartID(cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartItemsByCartID", reflect.TypeOf((*MockCartRepository)(nil).GetCartItemsByCartID), cartID)
}

// GetCartWithItems mocks base method.
func (m *MockCartRepository) GetCartWithItems(cartID string) (*entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartWithItems", cartID)
	ret0, _ := ret[0].(*entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartWithItems indicates an expected call of GetCartWithItems.
func (mr *MockCartRepositoryMockRecorder) GetCartWithItems(cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartWithItems", reflect.TypeOf((*MockCartRepository)(nil).GetCartWithItems), cartID)
}

// GetDiscountByCode mocks base method.
func (m *MockCartRepository) GetDiscountByCode(code string) (*entity.Discount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscountByCode", code)
	ret0, _ := ret[0].(*entity.Discount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscountByCode indicates an expected call of GetDiscountByCode.
func (mr *MockCartRepositoryMockRecorder) GetDiscountByCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscountByCode", reflect.TypeOf((*MockCartRepository)(nil).GetDiscountByCode), code)
}

// GetProductVariantByID mocks base method.
func (m *MockCartRepository) GetProductVariantByID(variantID string) (*entity.ProductVariant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductVariantByID", variantID)
	ret0, _ := ret[0].(*entity.ProductVariant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductVariantByID indicates an expected call of GetProductVariantByID.
func (mr *MockCartRepositoryMockRecorder) GetProductVariantByID(variantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductVariantByID", reflect.TypeOf((*MockCartRepository)(nil).GetProductVariantByID), variantID)
}

// UpdateCartItem mocks base method.
func (m *MockCartRepository) UpdateCartItem(item *entity.CartItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartItem", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCartItem indicates an expected call of UpdateCartItem.
func (mr *MockCartRepositoryMockRecorder) UpdateCartItem(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartItem", reflect.TypeOf((*MockCartRepository)(nil).UpdateCartItem), item)
}
