// Code generated by MockGen. DO NOT EDIT.
// Source: snap_client_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	midtrans "github.com/midtrans/midtrans-go"
	snap "github.com/midtrans/midtrans-go/snap"
)

// MockSnapClientInterface is a mock of SnapClientInterface interface.
type MockSnapClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSnapClientInterfaceMockRecorder
}

// MockSnapClientInterfaceMockRecorder is the mock recorder for MockSnapClientInterface.
type MockSnapClientInterfaceMockRecorder struct {
	mock *MockSnapClientInterface
}

// NewMockSnapClientInterface creates a new mock instance.
func NewMockSnapClientInterface(ctrl *gomock.Controller) *MockSnapClientInterface {
	mock := &MockSnapClientInterface{ctrl: ctrl}
	mock.recorder = &MockSnapClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnapClientInterface) EXPECT() *MockSnapClientInterfaceMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockSnapClientInterface) CreateTransaction(req *snap.Request) (*snap.Response, *midtrans.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", req)
	ret0, _ := ret[0].(*snap.Response)
	ret1, _ := ret[1].(*midtrans.Error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockSnapClientInterfaceMockRecorder) CreateTransaction(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockSnapClientInterface)(nil).CreateTransaction), req)
}