// Code generated by MockGen. DO NOT EDIT.
// Source: rajaongkir_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	response "github.com/hanifbg/landing_backend/internal/model/response"
)

// MockRajaOngkirClientInterface is a mock of RajaOngkirClientInterface interface.
type MockRajaOngkirClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRajaOngkirClientInterfaceMockRecorder
}

// MockRajaOngkirClientInterfaceMockRecorder is the mock recorder for MockRajaOngkirClientInterface.
type MockRajaOngkirClientInterfaceMockRecorder struct {
	mock *MockRajaOngkirClientInterface
}

// NewMockRajaOngkirClientInterface creates a new mock instance.
func NewMockRajaOngkirClientInterface(ctrl *gomock.Controller) *MockRajaOngkirClientInterface {
	mock := &MockRajaOngkirClientInterface{ctrl: ctrl}
	mock.recorder = &MockRajaOngkirClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRajaOngkirClientInterface) EXPECT() *MockRajaOngkirClientInterfaceMockRecorder {
	return m.recorder
}

// CalculateShippingCost mocks base method.
func (m *MockRajaOngkirClientInterface) CalculateShippingCost(origin, destination string, weight int, courier string) ([]response.RajaOngkirCost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateShippingCost", origin, destination, weight, courier)
	ret0, _ := ret[0].([]response.RajaOngkirCost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateShippingCost indicates an expected call of CalculateShippingCost.
func (mr *MockRajaOngkirClientInterfaceMockRecorder) CalculateShippingCost(origin, destination, weight, courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateShippingCost", reflect.TypeOf((*MockRajaOngkirClientInterface)(nil).CalculateShippingCost), origin, destination, weight, courier)
}

// GetCities mocks base method.
func (m *MockRajaOngkirClientInterface) GetCities(provinceID, cityID string) ([]response.RajaOngkirCity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCities", provinceID, cityID)
	ret0, _ := ret[0].([]response.RajaOngkirCity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCities indicates an expected call of GetCities.
func (mr *MockRajaOngkirClientInterfaceMockRecorder) GetCities(provinceID, cityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCities", reflect.TypeOf((*MockRajaOngkirClientInterface)(nil).GetCities), provinceID, cityID)
}

// GetProvinces mocks base method.
func (m *MockRajaOngkirClientInterface) GetProvinces(provinceID string) ([]response.RajaOngkirProvince, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvinces", provinceID)
	ret0, _ := ret[0].([]response.RajaOngkirProvince)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProvinces indicates an expected call of GetProvinces.
func (mr *MockRajaOngkirClientInterfaceMockRecorder) GetProvinces(provinceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvinces", reflect.TypeOf((*MockRajaOngkirClientInterface)(nil).GetProvinces), provinceID)
}

// GetDistricts mocks base method.
func (m *MockRajaOngkirClientInterface) GetDistricts(cityID string) ([]response.RajaOngkirDistrict, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistricts", cityID)
	ret0, _ := ret[0].([]response.RajaOngkirDistrict)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistricts indicates an expected call of GetDistricts.
func (mr *MockRajaOngkirClientInterfaceMockRecorder) GetDistricts(cityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistricts", reflect.TypeOf((*MockRajaOngkirClientInterface)(nil).GetDistricts), cityID)
}
